### ISSUE TITLE
Add a docker-compose to ease local development

### ISSUE THREAD

**Issue by thicolares** [meilisearch/meilisearch-ruby#250]
### Description
Ease collaboration and local development by utilizing virtualization with Docker. So we don't need to install basic dependencies and can keep them up-to-date by design.

### Tasks
- [ ] Create a docker-composer file containing (1) a ruby container and (2) a meilisearch container talking to each other;
- [ ] Expose basic settings, e.g. meilisearch service's host and port, via ENV variables;
- [ ] Update the CONTRIBUTING.md page with related tips.

### Other
I believe there're other improvements related to this topic, but maybe that's already a good starting point :)
