### ISSUE TITLE
Deprecate the usage of the camelCase attributes

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-ruby#320]
We currently support multiple ways of sending the search attributes:

- `index.search('abc', { attributesToCrop: ['description'], cropLength: 5 })`
- `index.search('abc', { attributes_to_highlight: ['description'] })`

and incorrect and weird ways like:

- `index.search('abc', { distinct_ATTribute: 'title' })`

Since this is not a ruby style of having attributes, we should eliminate it!

### TODO:

- [ ] Print warning messages when the user called a method with a different typographical convention than `snake_case`.
- [ ] Replace the old way with the new way in the `.code-samples.meilisearch.yml`

After the two initial steps:

- [ ] Drop the support to other styles (removing the code and the warnings).

**Comment by brunoocasali** [comment]
Fixed by https://github.com/meilisearch/meilisearch-ruby/pull/377 and #470
